apiVersion: v1
kind: ConfigMap
metadata:
  name: lumofy-index
data:
  index.html: |
    <!doctype html>
    <html lang="en">
    <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <title>Hello from Lumofy</title>
      <style>
        body {
          margin: 0;
          height: 100vh;
          display: grid;
          place-items: center;
          background: #ffffff;   /* white background */
          color: #000000;        /* black text */
          font-family: system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif;
        }
        h1 { font-size: 3rem; letter-spacing: .5px; }
      </style>
    </head>
    <body>
      <h1>hello from lumofy</h1>
    </body>
    </html>
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-lumofy
  labels:
    app: nginx-lumofy
spec:
  containers:
    - name: nginx
      image: nginx:1.27-alpine
      ports:
        - containerPort: 80
      volumeMounts:
        - name: web
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
  volumes:
    - name: web
      configMap:
        name: lumofy-index
        items:
          - key: index.html
            path: index.html
