apiVersion: v1
kind: Pod
metadata:
  name: nginx-lumofy
  namespace: my-app 
  labels:
    app: nginx-lumofy
spec:
  containers:
    - name: nginx
      image: nginx:1.27-alpine
      ports:
        - containerPort: 80
      volumeMounts:
        - name: web
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
  volumes:
    - name: web
      configMap:
        name: lumofy-index
        items:
          - key: index.html
            path: index.html
